CONFIG_TARGET_qualcommax=y
CONFIG_TARGET_qualcommax_ipq60xx=y
CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_qihoo_v6=y
# CONFIG_IPQ_MEM_PROFILE_1024 is not set
CONFIG_IPQ_MEM_PROFILE_512=y
CONFIG_KERNEL_IPQ_MEM_PROFILE=512
CONFIG_KERNEL_WERROR=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_CRYPTO_AUTH=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_OPENSSL=y
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_TFTP=y
CONFIG_LIBCURL_THREADED_RESOLVER=y
CONFIG_LIBCURL_TLS_SRP=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LUCI_LANG_zh_Hans=y
CONFIG_NSS_DRV_C2C_ENABLE=y
CONFIG_NSS_DRV_CAPWAP_ENABLE=y
CONFIG_NSS_DRV_CLMAP_ENABLE=y
CONFIG_NSS_DRV_DTLS_ENABLE=y
CONFIG_NSS_DRV_GRE_TUNNEL_ENABLE=y
# CONFIG_NSS_DRV_L2TP_ENABLE is not set
CONFIG_NSS_DRV_LSO_RX_ENABLE=y
CONFIG_NSS_DRV_OAM_ENABLE=y
CONFIG_NSS_DRV_PORTID_ENABLE=y
# CONFIG_NSS_DRV_PPTP_ENABLE is not set
CONFIG_NSS_DRV_QRFS_ENABLE=y
CONFIG_NSS_DRV_RMNET_ENABLE=y
CONFIG_NSS_DRV_SJACK_ENABLE=y
CONFIG_NSS_DRV_TLS_ENABLE=y
CONFIG_NSS_DRV_TSTAMP_ENABLE=y
# CONFIG_NSS_DRV_TUN6RD_ENABLE is not set
CONFIG_NSS_DRV_WIFI_LEGACY_ENABLE=y
# CONFIG_NSS_DRV_WIFI_MESH_ENABLE is not set
# CONFIG_NSS_FIRMWARE_VERSION_11_4 is not set
CONFIG_NSS_FIRMWARE_VERSION_12_2=y
# CONFIG_NSS_MEM_PROFILE_HIGH is not set
CONFIG_NSS_MEM_PROFILE_MEDIUM=y
# CONFIG_OPENSSL_OPTIMIZE_SPEED is not set
# CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM is not set
CONFIG_PACKAGE_6in4=y
# CONFIG_PACKAGE_6rd is not set
CONFIG_PACKAGE_WECHATPUSH_Enable_Host_Information_Detection=y
# CONFIG_PACKAGE_apk-openssl is not set
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_btop=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y
CONFIG_PACKAGE_default-settings=y
CONFIG_PACKAGE_default-settings-chn=y
CONFIG_PACKAGE_ip6tables-nft=y
# CONFIG_PACKAGE_ipq-wifi-8devices_mango is not set
CONFIG_PACKAGE_iputils-arping=y
CONFIG_PACKAGE_jq=y
CONFIG_PACKAGE_kmod-asn1-decoder=y
# CONFIG_PACKAGE_kmod-ath11k-pci is not set
CONFIG_PACKAGE_kmod-crypto-des=y
CONFIG_PACKAGE_kmod-crypto-md5=y
CONFIG_PACKAGE_kmod-crypto-sha256=y
# CONFIG_PACKAGE_kmod-dsa is not set
# CONFIG_PACKAGE_kmod-dsa-qca8k is not set
CONFIG_PACKAGE_kmod-fs-ksmbd=y
CONFIG_PACKAGE_kmod-fs-netfs=y
CONFIG_PACKAGE_kmod-fs-smbfs-common=y
CONFIG_PACKAGE_kmod-i2c-core=y
# CONFIG_PACKAGE_kmod-ifb is not set
CONFIG_PACKAGE_kmod-inet-diag=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
# CONFIG_PACKAGE_kmod-libphy is not set
# CONFIG_PACKAGE_kmod-mhi-bus is not set
CONFIG_PACKAGE_kmod-mii=y
# CONFIG_PACKAGE_kmod-net-selftests is not set
CONFIG_PACKAGE_kmod-netlink-diag=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-nf-tproxy=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_kmod-nls-ucs2-utils=y
CONFIG_PACKAGE_kmod-oid-registry=y
# CONFIG_PACKAGE_kmod-phy-aquantia is not set
# CONFIG_PACKAGE_kmod-phy-marvell is not set
# CONFIG_PACKAGE_kmod-phy-qca83xx is not set
# CONFIG_PACKAGE_kmod-phylink is not set
CONFIG_PACKAGE_kmod-qca-mcs=y
# CONFIG_PACKAGE_kmod-qca-nss-drv-igs is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-l2tpv2 is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-pptp is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-tun6rd is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-wifi-meshmgr is not set
CONFIG_PACKAGE_kmod-qca-nss-macsec=y
# CONFIG_PACKAGE_kmod-qrtr-mhi is not set
# CONFIG_PACKAGE_kmod-sched-core is not set
CONFIG_PACKAGE_kmod-tun=y
# CONFIG_PACKAGE_kmod-usb-dwc2 is not set
CONFIG_PACKAGE_kmod-usb-net=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
CONFIG_PACKAGE_kmod-usb-net-ipheth=y
# CONFIG_PACKAGE_kmod-usb2 is not set
CONFIG_PACKAGE_ksmbd-server=y
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libip6tc=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libnl-core=y
CONFIG_PACKAGE_libnl-genl=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci-app-cpufreq=y
CONFIG_PACKAGE_luci-app-ddns=y
# CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
# CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set
CONFIG_PACKAGE_luci-app-homeproxy=y
CONFIG_PACKAGE_luci-app-ksmbd=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Server is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geoview is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray is not set
# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
# CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
CONFIG_PACKAGE_luci-app-upnp=y
CONFIG_PACKAGE_luci-app-wechatpush=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-cpufreq-zh-cn=y
CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
CONFIG_PACKAGE_luci-i18n-homeproxy-zh-cn=y
CONFIG_PACKAGE_luci-i18n-ksmbd-zh-cn=y
CONFIG_PACKAGE_luci-i18n-package-manager-zh-cn=y
CONFIG_PACKAGE_luci-i18n-upnp-zh-cn=y
CONFIG_PACKAGE_luci-i18n-wechatpush-zh-cn=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_miniupnpd-nftables=y
CONFIG_PACKAGE_openssh-client=y
CONFIG_PACKAGE_openssh-keygen=y
CONFIG_PACKAGE_opkg=y
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_sing-box=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_wsdd2=y
CONFIG_PACKAGE_xtables-nft=y
CONFIG_SING_BOX_BUILD_ACME=y
CONFIG_SING_BOX_BUILD_CLASH_API=y
CONFIG_SING_BOX_BUILD_ECH=y
CONFIG_SING_BOX_BUILD_GVISOR=y
CONFIG_SING_BOX_BUILD_QUIC=y
CONFIG_SING_BOX_BUILD_REALITY_SERVER=y
